"""Initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-05 18:19:53.515567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('bank_operation_type', sa.String(length=255), nullable=True),
    sa.Column('bank_category', sa.String(length=255), nullable=True),
    sa.Column('bank_operation_kind', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('transaction_at', sa.DateTime(), nullable=True),
    sa.Column('payment_number', sa.String(length=128), nullable=True),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('signed_amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_purpose', sa.Text(), nullable=True),
    sa.Column('counterparty_inn', sa.String(length=32), nullable=True),
    sa.Column('counterparty_name', sa.String(length=512), nullable=True),
    sa.Column('mcc', sa.String(length=16), nullable=True),
    sa.Column('tax_code', sa.String(length=64), nullable=True),
    sa.Column('pnl_category', sa.String(length=255), nullable=True),
    sa.Column('cf_category', sa.String(length=255), nullable=True),
    sa.Column('include_in_pnl', sa.Boolean(), nullable=True),
    sa.Column('include_in_cf', sa.Boolean(), nullable=True),
    sa.Column('classification_status', sa.String(length=32), nullable=False),
    sa.Column('classification_source', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transactions_classification_status'), ['classification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_counterparty_inn'), ['counterparty_inn'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_counterparty_name'), ['counterparty_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_transactions_source_hash'), ['source_hash'], unique=True)

    op.create_table('classification_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('direction_filter', sa.String(length=16), nullable=False),
    sa.Column('match_field', sa.String(length=64), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('match_value', sa.String(length=512), nullable=False),
    sa.Column('include_in_pnl', sa.Boolean(), nullable=True),
    sa.Column('pnl_category', sa.String(length=255), nullable=True),
    sa.Column('include_in_cf', sa.Boolean(), nullable=True),
    sa.Column('cf_category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_rules_priority'), ['priority'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('source_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('received_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_imported_at'), ['imported_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_source_sha256'), ['source_sha256'], unique=False)

    op.create_table('planned_cash_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('counterparty', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_cash_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_cash_flows_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_cash_flows_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_cash_flows_start_date'), ['start_date'], unique=False)

    op.create_table('unit_economics_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('planned_units', sa.Integer(), nullable=False),
    sa.Column('pricing_method', sa.String(length=32), nullable=False),
    sa.Column('pricing_value_bp', sa.Integer(), nullable=True),
    sa.Column('manual_price_kopecks', sa.BigInteger(), nullable=True),
    sa.Column('rounding_step_kopecks', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_economics_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_economics_products_is_active'), ['is_active'], unique=False)

    op.create_table('import_batch_transactions',
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('import_batch_id', 'transaction_id')
    )
    with op.batch_alter_table('import_batch_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batch_transactions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('unit_economics_cost_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('calculation_type', sa.String(length=32), nullable=False),
    sa.Column('amount_kopecks', sa.BigInteger(), nullable=True),
    sa.Column('percentage_bp', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['unit_economics_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_economics_cost_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_economics_cost_items_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_economics_cost_items_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_economics_cost_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_economics_cost_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_unit_economics_cost_items_is_active'))

    op.drop_table('unit_economics_cost_items')
    with op.batch_alter_table('import_batch_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batch_transactions_transaction_id'))

    op.drop_table('import_batch_transactions')
    with op.batch_alter_table('unit_economics_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_economics_products_is_active'))

    op.drop_table('unit_economics_products')
    with op.batch_alter_table('planned_cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_cash_flows_start_date'))
        batch_op.drop_index(batch_op.f('ix_planned_cash_flows_is_active'))
        batch_op.drop_index(batch_op.f('ix_planned_cash_flows_direction'))

    op.drop_table('planned_cash_flows')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_source_sha256'))
        batch_op.drop_index(batch_op.f('ix_import_batches_imported_at'))

    op.drop_table('import_batches')
    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_classification_rules_is_active'))

    op.drop_table('classification_rules')
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_source_hash'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_posted_at'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_counterparty_name'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_counterparty_inn'))
        batch_op.drop_index(batch_op.f('ix_bank_transactions_classification_status'))

    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
