"""Add query indexes

Revision ID: 0002_query_indexes
Revises: 0001_initial
Create Date: 2026-08-05 21:07:58.821247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_query_indexes'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_rules_is_active'))
        batch_op.create_index('ix_classification_rules_active_priority', ['is_active', 'priority', 'id'], unique=False)

    with op.batch_alter_table('planned_cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_cash_flows_is_active'))
        batch_op.create_index('ix_planned_cash_flows_active_start_date', ['is_active', 'start_date', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_cash_flows', schema=None) as batch_op:
        batch_op.drop_index('ix_planned_cash_flows_active_start_date')
        batch_op.create_index(batch_op.f('ix_planned_cash_flows_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('classification_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_classification_rules_active_priority')
        batch_op.create_index(batch_op.f('ix_classification_rules_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###
